# site-wide variables
title: So Lab @ CUHK
email: carlos.chau.hk@gmail.com
google: Carlos CHAU
github: Carlos-Chau
twitter: CarlosChau6
#instagram: YourLabHandle
#youtube: YourLabChannel

# base directory where site is hosted
baseurl: /

# default front matter parameters for markdown files
defaults:
  # all markdown files
  - scope:
      path: ""
    values:
      description: Website of So Lab @ CUHK
      background: images/ken-cheung-10py7Mvmf1g-unsplash.jpg
      layout: default
  # markdown files in /_members
  - scope:
      type: "members"
    values:
      layout: member
  # markdown files in /_posts
  - scope:
      type: "posts"
    values:
      layout: post

# collections
collections:
  members:
    output: true

# sass settings
sass:
  sass_dir: css

# syntax highlighting
highlighter: rouge

# build settings
plugins:
  - jekyll-feed
  - jekyll-redirect-from
